clc;
clear all;
close all;
f1=input('Enter carrier frequency : ');
f2=input('Enter pulse frequency : ');
A=4;
t = 0:0.001:1;
x=A*sin(2*pi*f1*t);
y=(A/2)*square(2*pi*f2*t)+A/2;
z=x.*y;
subplot(3,1,1);
plot(t,x);
title('sine wave');
xlabel('time');
ylabel('amplitude');
subplot(3,1,2);
plot(t,y);
title('Digital signal');
xlabel('Time');
ylabel('Amplitude');
subplot(3,1,3);
plot(t,z);
title('ASK');
xlabel('Time');
ylabel('Smplitude');
